version: '3'
services:
  web:
    build: .
    ports:
      - "8095:80"
    restart: unless-stopped
  
  evidence-server:
    build:
      context: .
      dockerfile: Dockerfile.evidence
    volumes:
      - ./evidence:/data
    restart: unless-stopped 